version: '3.8'

services:
  db:
    image: banhmysuawx/postgres-pgbigm:14-alpine
    container_name: db_lab1
    restart: on-failure:5
    env_file:
      - environment/psql_db.env
    ports:
      - "28879:5432"
    volumes:
      - lab1_pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  lab1_pgdata: